# Generated by Django 3.0.5 on 2020-05-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200502_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='fruits', max_length=200, unique=True),
        ),
    ]
